/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'cider-styles': CiderStyle;
    ciders: Cider;
    boxes: Box;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'cider-styles': CiderStylesSelect<false> | CiderStylesSelect<true>;
    ciders: CidersSelect<false> | CidersSelect<true>;
    boxes: BoxesSelect<false> | BoxesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Define filter options for the ciders catalogue. Slug is used in URLs (?style=slug). Create styles before assigning ciders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cider-styles".
 */
export interface CiderStyle {
  id: number;
  label: string;
  /**
   * Lowercase, use underscores if needed (e.g. semi_dry).
   */
  slug: string;
  /**
   * Lower numbers appear first in filters.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ciders".
 */
export interface Cider {
  id: number;
  title: string;
  /**
   * URL segment, e.g. apple-dry
   */
  slug: string;
  /**
   * Managed under Catalog → Cider styles.
   */
  style: number | CiderStyle;
  shortDescription?: string | null;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  abv?: number | null;
  volumeMl?: number | null;
  /**
   * One per line or comma-separated.
   */
  tastingNotes?: string | null;
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  available?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Shop SKUs. A Stripe Price ID (price_…) is required for checkout — create the product in Stripe and paste it here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boxes".
 */
export interface Box {
  id: number;
  title: string;
  /**
   * URL: /shop/[slug]
   */
  slug: string;
  description?: string | null;
  /**
   * Shown on the site; should match the Stripe price.
   */
  priceEur: number;
  /**
   * Must be price_… (Checkout line_items). Not prod_… — Dashboard → Products → open product → Pricing → copy the price API ID.
   */
  stripePriceId?: string | null;
  inStock?: boolean | null;
  image?: (number | null) | Media;
  containsCiders?: (number | Cider)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  stripeCheckoutSessionId: string;
  status: 'paid' | 'pending' | 'cancelled';
  customerEmail?: string | null;
  amountTotalCents: number;
  currency?: string | null;
  /**
   * Cart summary from checkout.
   */
  lineItems?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cider-styles';
        value: number | CiderStyle;
      } | null)
    | ({
        relationTo: 'ciders';
        value: number | Cider;
      } | null)
    | ({
        relationTo: 'boxes';
        value: number | Box;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cider-styles_select".
 */
export interface CiderStylesSelect<T extends boolean = true> {
  label?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ciders_select".
 */
export interface CidersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  style?: T;
  shortDescription?: T;
  longDescription?: T;
  abv?: T;
  volumeMl?: T;
  tastingNotes?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  available?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boxes_select".
 */
export interface BoxesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  priceEur?: T;
  stripePriceId?: T;
  inStock?: T;
  image?: T;
  containsCiders?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  stripeCheckoutSessionId?: T;
  status?: T;
  customerEmail?: T;
  amountTotalCents?: T;
  currency?: T;
  lineItems?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Full URL, e.g. https://www.instagram.com/sodo_cider/
   */
  instagramUrl?: string | null;
  /**
   * Full URL to the page or profile.
   */
  facebookUrl?: string | null;
  siteName?: string | null;
  navCidersLabel?: string | null;
  navShopLabel?: string | null;
  navAboutLabel?: string | null;
  navContactLabel?: string | null;
  navCartLabel?: string | null;
  metaTitleHome?: string | null;
  metaDescriptionHome?: string | null;
  metaTitleCiders?: string | null;
  metaDescriptionCiders?: string | null;
  metaTitleAbout?: string | null;
  metaDescriptionAbout?: string | null;
  metaTitleContact?: string | null;
  metaDescriptionContact?: string | null;
  metaTitleShop?: string | null;
  metaDescriptionShop?: string | null;
  metaTitleCart?: string | null;
  metaDescriptionCart?: string | null;
  metaTitlePrivacy?: string | null;
  metaDescriptionPrivacy?: string | null;
  metaTitleTerms?: string | null;
  metaDescriptionTerms?: string | null;
  metaTitleShipping?: string | null;
  metaDescriptionShipping?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Reorder sections below. Hero / featured / pillars use fixed URLs in code where noted.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Each gray bar is one section: use the grip to drag, the row to expand/collapse, ⋯ for duplicate/remove. Add Hero + Three pillars for a full page. Featured boxes only show on the site when the shop is enabled. If nothing would render, defaults fill in once.
   */
  layout?:
    | (
        | {
            heroImage?: (number | null) | Media;
            heroEyebrow?: string | null;
            heroHeading?: string | null;
            heroLead?: string | null;
            heroExtraWhenShopEnabled?: string | null;
            heroExtraWhenShopDisabled?: string | null;
            ctaPrimaryShopEnabled?: string | null;
            ctaSecondaryShopEnabled?: string | null;
            ctaPrimaryShopDisabled?: string | null;
            ctaSecondaryShopDisabled?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeHero';
          }
        | {
            /**
             * This section appears only when the shop is enabled. Card and link URLs are fixed in code.
             */
            featuredSectionTitle?: string | null;
            featuredSectionSubtitle?: string | null;
            featuredSectionLinkText?: string | null;
            featuredBoxButtonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeFeaturedBoxes';
          }
        | {
            pillar1Title?: string | null;
            pillar1Body?: string | null;
            pillar2Title?: string | null;
            pillar2Body?: string | null;
            pillar3TitleWhenShopEnabled?: string | null;
            pillar3BodyWhenShopEnabled?: string | null;
            pillar3TitleWhenShopDisabled?: string | null;
            pillar3LinkTextWhenShopDisabled?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homePillars';
          }
      )[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  heading?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  heading?: string | null;
  intro?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  email?: string | null;
  phone?: string | null;
  /**
   * Multi-line address or other contact details.
   */
  address?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  instagramUrl?: T;
  facebookUrl?: T;
  siteName?: T;
  navCidersLabel?: T;
  navShopLabel?: T;
  navAboutLabel?: T;
  navContactLabel?: T;
  navCartLabel?: T;
  metaTitleHome?: T;
  metaDescriptionHome?: T;
  metaTitleCiders?: T;
  metaDescriptionCiders?: T;
  metaTitleAbout?: T;
  metaDescriptionAbout?: T;
  metaTitleContact?: T;
  metaDescriptionContact?: T;
  metaTitleShop?: T;
  metaDescriptionShop?: T;
  metaTitleCart?: T;
  metaDescriptionCart?: T;
  metaTitlePrivacy?: T;
  metaDescriptionPrivacy?: T;
  metaTitleTerms?: T;
  metaDescriptionTerms?: T;
  metaTitleShipping?: T;
  metaDescriptionShipping?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        homeHero?:
          | T
          | {
              heroImage?: T;
              heroEyebrow?: T;
              heroHeading?: T;
              heroLead?: T;
              heroExtraWhenShopEnabled?: T;
              heroExtraWhenShopDisabled?: T;
              ctaPrimaryShopEnabled?: T;
              ctaSecondaryShopEnabled?: T;
              ctaPrimaryShopDisabled?: T;
              ctaSecondaryShopDisabled?: T;
              id?: T;
              blockName?: T;
            };
        homeFeaturedBoxes?:
          | T
          | {
              featuredSectionTitle?: T;
              featuredSectionSubtitle?: T;
              featuredSectionLinkText?: T;
              featuredBoxButtonLabel?: T;
              id?: T;
              blockName?: T;
            };
        homePillars?:
          | T
          | {
              pillar1Title?: T;
              pillar1Body?: T;
              pillar2Title?: T;
              pillar2Body?: T;
              pillar3TitleWhenShopEnabled?: T;
              pillar3BodyWhenShopEnabled?: T;
              pillar3TitleWhenShopDisabled?: T;
              pillar3LinkTextWhenShopDisabled?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  heading?: T;
  heroImage?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  email?: T;
  phone?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}